### ISSUE TITLE
[Documentation] Need basic documentation

### ISSUE THREAD

**Issue by mayuso** [dancarpenter21/lol-api-java#1]
I´d love to use this as an interface between riot data and a couple programs in java i want to develop.

The problem is that there is no documentation, so i have no idea how to use it or even if it is possible to use this code as an exernal library.

Also, if i finally get to understand and use this code, i´d be glad to help improve it.

**Comment by dancarpenter21** [comment]
Thanks for the interest!

This project is definitely a work in progress so documentation is sadly lacking. This project most certainly is meant to be used by other code as an external library; however, so if something isn't clear, feel free to ask. The README has the basic usage example. If you care to explain what it is that you want to do I'm happy to fill in the documentation that you'd need to get up and running!

**Comment by mayuso** [comment]
Thank you for answering so fast.

I just need to get information about games (history or current)for a specific summoner. I also read the README, but i only found a 1000 line example without a single comment, so thats kinda hard to understand.

Sorry for any english mistakes.

**Comment by dancarpenter21** [comment]
Hey thanks for the feedback. I checked in an example application that looks up a player's match history and current game status. It's in the `examples` package. Feel free to post any further questions.

**Comment by mayuso** [comment]
Oh, yeah, i see the push :) I will see how that works asap, can´t right now. Thank you! I hope i can help you too soon :)
